import { Company, FinancialRatios } from '@/types/company';
import { SWOTData } from '@/hooks/useStockData';

interface PDFData {
  company: Company;
  ratios: FinancialRatios | null;
  swot: SWOTData | null;
  generatedAt: Date;
}

export function generatePDFContent(data: PDFData): string {
  const { company, ratios, swot, generatedAt } = data;
  
  const safeToFixed = (val: number | null | undefined, decimals: number = 2) => {
    if (val === null || val === undefined || isNaN(val)) return 'N/A';
    return val.toFixed(decimals);
  };

  let content = `
LAPORAN ANALISIS PERUSAHAAN
============================

Perusahaan: ${company.name}
Ticker: ${company.ticker}
Bursa: ${company.exchange || 'N/A'}
Sektor: ${company.sector || 'N/A'}
Tanggal: ${generatedAt.toLocaleDateString('id-ID')}

-----------------------------
RINGKASAN HARGA
-----------------------------
Harga Saat Ini: ${company.currency || 'USD'} ${safeToFixed(company.currentPrice)}
Perubahan: ${company.priceChangePercent && company.priceChangePercent >= 0 ? '+' : ''}${safeToFixed(company.priceChangePercent)}%
Market Cap: ${company.marketCap ? `${(company.marketCap / 1e9).toFixed(1)}B` : 'N/A'}
P/E Ratio: ${safeToFixed(company.peRatio)}
Dividend Yield: ${company.divYield ? `${safeToFixed(company.divYield)}%` : 'N/A'}
`;

  if (ratios) {
    content += `
-----------------------------
RASIO KEUANGAN
-----------------------------
ROE (Return on Equity): ${safeToFixed(ratios.roe)}%
ROA (Return on Assets): ${safeToFixed(ratios.roa)}%
Debt to Equity: ${safeToFixed(ratios.debtToEquity)}
Current Ratio: ${safeToFixed(ratios.currentRatio)}
Net Profit Margin: ${safeToFixed(ratios.netProfitMargin)}%
P/E Ratio: ${safeToFixed(ratios.peRatio)}
P/B Ratio: ${safeToFixed(ratios.pbRatio)}
`;
  }

  if (swot) {
    content += `
-----------------------------
ANALISIS SWOT
-----------------------------

KEKUATAN (Strengths):
${swot.strengths.map((s, i) => `${i + 1}. ${s}`).join('\n')}

KELEMAHAN (Weaknesses):
${swot.weaknesses.map((w, i) => `${i + 1}. ${w}`).join('\n')}

PELUANG (Opportunities):
${swot.opportunities.map((o, i) => `${i + 1}. ${o}`).join('\n')}

ANCAMAN (Threats):
${swot.threats.map((t, i) => `${i + 1}. ${t}`).join('\n')}

Ringkasan: ${swot.summary || 'N/A'}
`;
  }

  content += `
-----------------------------
DISCLAIMER
-----------------------------
Laporan ini dihasilkan oleh Stock Analyzer untuk tujuan edukasi.
Bukan merupakan saran investasi. Lakukan riset mandiri sebelum berinvestasi.

Generated by Stock Analyzer - ${generatedAt.toISOString()}
`;

  return content;
}

export function downloadAsTextFile(content: string, filename: string) {
  const blob = new Blob([content], { type: 'text/plain;charset=utf-8' });
  const url = URL.createObjectURL(blob);
  const link = document.createElement('a');
  link.href = url;
  link.download = filename;
  document.body.appendChild(link);
  link.click();
  document.body.removeChild(link);
  URL.revokeObjectURL(url);
}

export function shareContent(title: string, text: string, url?: string) {
  if (navigator.share) {
    navigator.share({
      title,
      text,
      url: url || window.location.href,
    }).catch(console.error);
  } else {
    // Fallback: copy to clipboard
    navigator.clipboard.writeText(text).then(() => {
      alert('Konten berhasil disalin ke clipboard!');
    }).catch(console.error);
  }
}
